  /* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.3.0.0 (NJsonSchema v10.1.11.0 (Newtonsoft.Json v11.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming

export interface CustomerDto {
  name: string;
  address: string | undefined;
  phone?: string | undefined;
  email: string | undefined;
}

export interface QuoteDto {
  id: string;
  quoteNumber?: number;
  statusCode: QuoteStatusCode;
  lastModifiedAt: Date;
  customer: CustomerDto;
  mobilePhone?: QuoteMobilePhoneDto;
  accessories?: QuoteAccessoryDto[];
  note?: string | undefined;
}

export enum QuoteStatusCode {
  Draft = 'Draft',
  Open = 'Open',
  Accepted = 'Accepted',
  Expired = 'Expired',
}

export interface QuoteMobilePhoneDto {
  serialNo: string;
  model: string;
  price: number;
  discount?: number | undefined;
}

export interface QuoteAccessoryDto {
  id: number;
  description: string;
  quantity: number;
  unitPrice: number;
}

export interface AddQuoteResponse {
  id: string;
}

export interface AddQuoteCommand {
  customerName: string;
  customerAddress: string;
  customerPhone?: string | undefined;
  customerEmail: string;
  mobilePhoneMake?: string | undefined;
  mobilePhoneModel?: string | undefined;
  price?: number | undefined;
  discount?: number | undefined;
}

export interface UpdateQuoteCustomerCommand {
  quoteId: string;
  customerName: string;
  customerAddress: string;
  customerPhone?: string | undefined;
  customerEmail: string;
}

export interface UpdateQuoteMobilePhoneCommand {
  quoteId: string;
  serialNo: string;
  model: string;
  price: number;
  discount?: number | undefined;
}

export interface QuoteSummaryDto {
  id: string;
  quoteNumber?: number;
  statusCode: QuoteStatusCode;
  lastModifiedAt: Date;
  customerName: string;
  mobilePhoneDescription?: string;
}

export interface UpsertQuoteAccessoriesCommand {
  quoteId: string;
  accessories?: QuoteAccessoryDto[];
}

export interface UpdateQuoteNoteCommand {
  quoteId: string;
  note?: string | undefined;
}

export interface AcceptQuoteCommand {
  quoteId: string;
}

export interface UserProfileDto {
  id: string;
  name: string;
  userPictureUrl: string | undefined;
}
